import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

// Allow up to 5 minutes — AI generation can take 60–120 s for long posts
export const maxDuration = 300;

const MAX_KB_CHARS = 40_000;
const DEFAULT_MODEL = "anthropic/claude-sonnet-4-6";
const ALLOWED_MODELS = new Set([
  "anthropic/claude-sonnet-4-6",
  "anthropic/claude-opus-4-7",
  "openai/gpt-4.1",
  "openai/gpt-4o-mini",
  "anthropic/claude-haiku-4.5",
]);

function resolveModel(raw: unknown): string {
  if (typeof raw !== "string" || !raw.trim()) return DEFAULT_MODEL;
  return ALLOWED_MODELS.has(raw.trim()) ? raw.trim() : DEFAULT_MODEL;
}

function stripCodeFences(raw: string): string {
  let s = raw.trim();
  s = s.replace(/^```(?:json)?\s*\n?/i, "").replace(/\n?```\s*$/i, "").trim();
  return s;
}

function repairJson(s: string): string {
  let t = s.trim();
  const start = t.indexOf("{");
  if (start === -1) return t;
  t = t.slice(start);
  let depth = 0, end = -1;
  for (let i = 0; i < t.length; i++) {
    const c = t[i];
    if (c === '"') {
      i++;
      while (i < t.length) {
        if (t[i] === "\\" && i + 1 < t.length) { i += 2; continue; }
        if (t[i] === '"') break;
        i++;
      }
      continue;
    }
    if (c === "{") depth++;
    else if (c === "}") { depth--; if (depth === 0) { end = i; break; } }
  }
  if (end !== -1) return t.slice(0, end + 1);
  const need = Math.max(0, (t.match(/\{/g) ?? []).length - (t.match(/\}/g) ?? []).length);
  return need > 0 ? t + "}".repeat(need) : t;
}

function normalizeBlocks(content: unknown): unknown[] {
  if (!Array.isArray(content)) return [];
  return content.map((block) => {
    if (!block || typeof block !== "object") return block;
    const b = block as Record<string, unknown>;
    if (b.type === "callout" && b.variant === "info") return { ...b, variant: "insight" };
    return b;
  });
}

function buildSystemPrompt(knowledgeBaseBlock: string): string {
  return `You are an expert SEO content writer. Use the following knowledge base as the authoritative reference for brand voice, services, tone, and approved proof points. If the knowledge base is empty, write high-quality general content for the given topic.

[KNOWLEDGE BASE]
${knowledgeBaseBlock || "(none provided — write authoritative, well-researched content for the given topic and keyword)"}
[END KNOWLEDGE BASE]

NON-NEGOTIABLE RULES:

1. CONTENT QUALITY
- Do not fabricate statistics, case studies, or credentials. Only use facts that are well-established or sourced.
- Never provide advice that could constitute legal, medical, or financial guidance unless the knowledge base authorizes it.
- Write in the brand voice described in the knowledge base. If none, default to authoritative, helpful, and clear.

2. FORMATTING
- Do not use bold text in body content.
- Use lists sparingly (3–7 items max). Most sections should be prose.
- Reserve tables for comparing options, strategies, or metrics.
- Use pullquotes only for genuinely insightful key takeaways.

3. STRUCTURE
- Open with a strong 2+ paragraph introduction naming the problem and previewing the solution.
- Use H2 sections to build a logical argument. Use H3 only when nested detail is needed under an H2.
- Include a FAQ section near the end with 4–6 realistic questions as H3 headings with paragraph answers.
- End with a closing CTA paragraph.

4. SEO
- The primary keyword must appear in the title, meta description, first paragraph, and at least one H2.
- Include 2–5 external links to credible, authoritative sources. Use descriptive anchor text via [anchor](https://url) markdown.
- Do NOT include internal links — those are added by a separate tool.

5. SEO BRIEF COMPLIANCE (CRITICAL — applies when a SEO BRIEF is provided in the user message)
- The SEO BRIEF is NOT optional guidance. It is a strict checklist generated by analyzing the top-ranking competitor pages, and your output is scored against it.
- You MUST use every NLP term listed in the brief at least the minimum number of times specified. Falling short on any term will hurt the content score.
- You MUST answer every question listed in the brief — either as a dedicated H3 in the FAQ section or organically in the body.
- You MUST cover every fact listed in the brief, paraphrased into prose (never copy verbatim). Distribute facts naturally across intro, body, and FAQ.
- Before finalizing your output, verify that every term, question, and fact from the brief is present. Treat the brief as a hard constraint, not a suggestion.

6. OUTPUT FORMAT
Output ONLY a valid JSON object conforming to this shape:
{
  "title": "string — SEO-optimized, includes primary keyword, under 70 chars",
  "excerpt": "string under 160 chars",
  "metaDescription": "string under 155 chars, includes primary keyword",
  "content": [
    { "type": "paragraph", "text": "..." },
    { "type": "h2", "text": "..." },
    { "type": "h3", "text": "..." },
    { "type": "list", "items": ["...", "..."] },
    { "type": "numbered", "items": ["...", "..."] },
    { "type": "pullquote", "text": "..." },
    { "type": "callout", "text": "...", "variant": "warning|tip|insight" },
    { "type": "stat-row", "stats": [{ "value": "...", "label": "..." }] },
    { "type": "divider" },
    { "type": "table", "tableHeaders": ["..."], "tableRows": [["..."]] }
  ]
}
No markdown fences. No preamble. No trailing commentary.`;
}

function buildUserMessage(opts: {
  topic: string;
  primaryKeyword: string;
  category?: string;
  tone?: string;
  targetWordCount?: number;
  audience?: string;
  customInstructions?: string;
  seoGuidelines?: string;
}): string {
  const parts: string[] = [
    `Topic: ${opts.topic}`,
    `Primary keyword: ${opts.primaryKeyword}`,
    opts.category ? `Category: ${opts.category}` : `Category: let AI decide based on topic`,
    opts.tone ? `Tone: ${opts.tone}` : `Tone: authoritative but compassionate, evidence-based`,
    `Target word count: ${opts.targetWordCount ?? 2000}`,
    opts.audience ? `Audience: ${opts.audience}` : `Audience: the target readers for this brand (derive from knowledge base, or default to general informed adult readers)`,
  ];

  if (opts.seoGuidelines?.trim()) {
    parts.push(
      `\n=== CONTENT BRIEF (MANDATORY — strict compliance required, see system prompt rule 5) ===\n${opts.seoGuidelines.trim().slice(0, 20000)}\n=== END CONTENT BRIEF ===`,
    );
  }

  if (opts.customInstructions?.trim()) {
    parts.push(`\nAdditional instructions:\n${opts.customInstructions.trim()}`);
  }

  parts.push(`\nGenerate the blog post now. Output only the JSON object as specified.`);
  return parts.join("\n");
}

export async function POST(request: Request) {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ error: "OPENROUTER_API_KEY is not configured." }, { status: 500 });
  }

  let body: Record<string, unknown>;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  const topic = typeof body.topic === "string" ? body.topic.trim() : "";
  const primaryKeyword = typeof body.primaryKeyword === "string" ? body.primaryKeyword.trim() : "";
  if (!topic || !primaryKeyword) {
    return NextResponse.json({ error: "topic and primaryKeyword are required." }, { status: 400 });
  }

  const category = typeof body.category === "string" ? body.category : undefined;
  const tone = typeof body.tone === "string" ? body.tone : undefined;
  const targetWordCount = typeof body.targetWordCount === "number" ? body.targetWordCount : undefined;
  const audience = typeof body.audience === "string" ? body.audience : undefined;
  const customInstructions = typeof body.customInstructions === "string" ? body.customInstructions : undefined;
  const seoGuidelines = typeof body.seoGuidelines === "string" ? body.seoGuidelines : undefined;
  const model = resolveModel(body.model);

  // Fetch brand knowledge base
  let knowledgeBaseBlock = "";
  try {
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
    const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY ?? "";
    if (supabaseUrl && serviceKey) {
      const adminClient = createClient(supabaseUrl, serviceKey, {
        auth: { autoRefreshToken: false, persistSession: false },
      });
      const { data: kbRows } = await adminClient
        .from("blog_knowledge_base")
        .select("title, content")
        .eq("is_active", true);
      if (kbRows && kbRows.length > 0) {
        for (const row of kbRows as { title?: string; content?: string }[]) {
          knowledgeBaseBlock += `## ${row.title ?? ""}\n${row.content ?? ""}\n\n`;
        }
        if (knowledgeBaseBlock.length > MAX_KB_CHARS) {
          knowledgeBaseBlock = knowledgeBaseBlock.slice(0, MAX_KB_CHARS);
        }
      }
    }
  } catch (err) {
    console.warn("[rewrite-blog-post] knowledge base fetch failed (continuing without):", err);
  }

  const systemPrompt = buildSystemPrompt(knowledgeBaseBlock);
  const userMessage = buildUserMessage({ topic, primaryKeyword, category, tone, targetWordCount, audience, customInstructions, seoGuidelines });

  let orRes: Response;
  try {
    orRes = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      "HTTP-Referer": process.env.NEXT_PUBLIC_SITE_URL ?? "https://mountainviewtreatment.com",
      "X-Title": `${process.env.NEXT_PUBLIC_SITE_ID ?? "admin"} - Blog Rewriter`,
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userMessage },
        ],
        max_tokens: 12000,
        temperature: 0.4,
      }),
    });
  } catch (fetchErr) {
    console.error("[rewrite-blog-post] fetch to OpenRouter failed:", fetchErr);
    return NextResponse.json({ error: `Could not reach OpenRouter: ${String(fetchErr)}` }, { status: 502 });
  }

  const orText = await orRes.text();

  if (!orRes.ok) {
    console.error("[rewrite-blog-post] OpenRouter non-OK:", orRes.status, orText.slice(0, 500));
    return NextResponse.json({ error: `OpenRouter error (${orRes.status}): ${orText.slice(0, 400)}` }, { status: 502 });
  }

  let orJson: Record<string, unknown>;
  try {
    orJson = JSON.parse(orText) as Record<string, unknown>;
  } catch {
    console.error("[rewrite-blog-post] OpenRouter response not JSON:", orText.slice(0, 500));
    return NextResponse.json({ error: `OpenRouter returned non-JSON response: ${orText.slice(0, 300)}` }, { status: 502 });
  }

  const mc = (orJson?.choices as unknown[])?.[0];
  const rawContent: string = ((mc as Record<string, unknown>)?.message as Record<string, unknown>)?.content as string ?? "";

  if (!rawContent) {
    console.error("[rewrite-blog-post] Empty content from OpenRouter:", JSON.stringify(orJson).slice(0, 500));
    return NextResponse.json({ error: "AI returned an empty response. The model may have hit a content filter or token limit." }, { status: 502 });
  }

  let parsed: Record<string, unknown>;
  try {
    const stripped = stripCodeFences(rawContent);
    parsed = JSON.parse(stripped) as Record<string, unknown>;
  } catch {
    try {
      parsed = JSON.parse(repairJson(stripCodeFences(rawContent))) as Record<string, unknown>;
    } catch {
      return NextResponse.json({ error: "Failed to parse AI-generated JSON.", raw: rawContent.slice(0, 2000) }, { status: 502 });
    }
  }

  const title = String(parsed.title ?? "").trim();
  const excerpt = String(parsed.excerpt ?? "").trim();
  const metaDescription = String(parsed.metaDescription ?? parsed.meta_description ?? "").trim();
  const content = normalizeBlocks(parsed.content);

  if (!title || content.length === 0) {
    return NextResponse.json({ error: "AI response missing title or content blocks." }, { status: 502 });
  }

  return NextResponse.json({ ok: true, title, excerpt, metaDescription, content });
}
