import type { MetadataRoute } from "next";
import { mergeRobotsDisallow } from "@sweetmedia/admin-core";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL!;

/**
 * Robots policy — allow indexing of public marketing pages; block /admin,
 * /api/, and Next.js build assets (via mergeRobotsDisallow). Sitemap is
 * generated by the admin-core sitemap util and surfaced via /sitemap.xml.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: mergeRobotsDisallow(["/admin", "/admin/", "/api/"]),
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
  };
}
